# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web Deployment to Firebase

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    environment: release

    steps:
      # Checkout the code from the main branch
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      # Set up Flutter on the runner
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build the Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release

      # Set up Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy


